### ISSUE TITLE
"Invalid token" errors on 1.0.4

### ISSUE THREAD

**Issue by A-Zak** [ducdigital/gulp-sentry-release#10]
Hey,
I keep getting "Invalid token" errors when trying to upload source maps. Not sure what the problem was, but reverting to 1.0.2 fixed it for me.

**Comment by danzel** [comment]
The project now uses Auth Tokens instead of API Keys.
Go create one on here: https://sentry.io/api/

Was mentioned off hand in #8, I'll send a readme update PR.
